def test_placeholder():
    assert True


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Generated Page</title>
</head>
<body>
    <h1>Hello, World!</h1>
    <p>This page was generated by generate_html.py</p>
</body>
</html>
"""


def generate_html(output_path="output.html"):
    with open(output_path, "w") as f:
        f.write(HTML_TEMPLATE)
    return output_path


if __name__ == "__main__":
    generate_html()
